version: "3"
services:
  appdb:
    image: postgres:12.2-alpine
    container_name: "appdb"
    environment:
      - POSTGRES_USER=test01
      - POSTGRES_PASSWORD=test01
      - POSTGRES_DB=test01
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

volumes:
  database:
    driver: local